// This code has been generated by the C2W code generator.
// Do not edit manually!

package SimpleAdder;

import SimpleAdder.AdderBase;
import SimpleAdder.AdderInput;
import c2w.hla.InteractionRoot;
import c2w.hla.SubscribedInteractionFilter;

public class Adder extends AdderBase {

	private SubscribedInteractionFilter _subscribedInteractionFilter = new SubscribedInteractionFilter();
	int sum;
	
	// constructor
	public Adder( String federation_id, String federate_id ) throws Exception {
		super(federation_id, federate_id);
                }
        
       // constructor
	public Adder(  String[] federationInfo ) throws Exception {
		super(federationInfo);
	}

	private void execute() throws Exception {
		System.out.println("execute==>");
		double logicalTime = 0;
		InteractionRoot interaction = null;
		ObjectReflector reflector = null;

		AdvanceTimeRequest atr = new AdvanceTimeRequest(logicalTime);
		putAdvanceTimeRequest(atr);

		readyToPopulate();
		// NOTE: do initialization that depends on other federates here
		readyToRun();

		startAdvanceTimeThread();

		// executes until the federate terminates
		while (true) {
			// NOTE: change the federate logical step size below
			logicalTime += 1.0;

			atr.requestSyncStart();

			// NOTE: send interactions beyond this line (see hla_interaction_send)
			// executes until all interactions from the previous time step are handled

			
			while ((interaction = getNextInteractionNoWait()) != null) {
				
			    if(interaction instanceof AdderInput) {
			        handleInteractionClass((AdderInput)interaction);
				}
			}
			
			
			
			// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
			// DO NOT MODIFY FILE BEYOND THIS LINE
			// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
			AdvanceTimeRequest newATR = new AdvanceTimeRequest(logicalTime);
			putAdvanceTimeRequest(newATR);
			atr.requestSyncEnd();
			atr = newATR;
		}
	}

	
	private void handleInteractionClass(AdderInput interaction) {
		sum += interaction.get_value();
		System.out.println("sum=" + sum);
	}
	 
	
	private void handleObjectClass(AdderInput object) {
	    // user implements this function
	}
	
	public static void main(String[] args) {
		try {
			System.out.println("Adder main");
			Adder instance = new Adder(args);
			instance.execute();
		} catch (Exception e) {
			System.err.println("Exception caught: " + e.getMessage());
			e.printStackTrace();
		}
	}
}
